name: Prebuild Binaries

on:
  pull_request:

jobs:
  prebuild-linux:
    name: Prebuild Binaries for Linux
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Setup Dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update -y -qq
          sudo apt-get install -y g++-multilib gcc-multilib libcups2-dev libcups2-dev:i386 libc6-dev-i386 linux-libc-dev linux-libc-dev:i386
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: actions/checkout@v1
      - run: npm i
      - name: Prebuild
        run: |
          npm run apply-patches
          npm run prebuild -- --strip -r node -t 47 -t 48 -t 51 -t 57 -t 59 -t 64 -t 67 -t 72 -t 79 -t 83 -t 88 -t 93 -t 102 --arch ia32
          npm run prebuild -- --strip -r electron -t 47 -t 48 -t 49 -t 50 -t 51 -t 53 -t 54 -t 57 -t 64 -t 69 -t 70 -t 73 -t 75 -t 76 -t 80 -t 82 -t 85 -t 87 -t 89 -t 97 -t 98 -t 99 -t 101 -t 102 -t 103 --arch ia32
          npm run prebuild -- --strip -r node -t 47 -t 48 -t 51 -t 57 -t 59 -t 64 -t 67 -t 72 -t 79 -t 83 -t 88 -t 93 -t 102 --arch x64
          npm run prebuild -- --strip -r electron -t 47 -t 48 -t 49 -t 50 -t 51 -t 53 -t 54 -t 57 -t 64 -t 69 -t 70 -t 73 -t 75 -t 76 -t 80 -t 82 -t 85 -t 87 -t 89 -t 97 -t 98 -t 99 -t 101 -t 102 -t 103 --arch x64
  prebuild-macos:
    name: Prebuild Binaries for macOS
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: actions/checkout@v1
      - run: npm i
      - name: Prebuild
        run: |
          npm run apply-patches
          npm run prebuild -- --strip -r node -t 47 -t 48 -t 51 -t 57 -t 59 -t 64 -t 67 -t 72 -t 79 -t 83 -t 88 -t 93 -t 102 --arch x64
          npm run prebuild -- --strip -r electron -t 47 -t 48 -t 49 -t 50 -t 51 -t 53 -t 54 -t 57 -t 64 -t 69 -t 70 -t 73 -t 75 -t 76 -t 80 -t 82 -t 85 -t 87 -t 89 -t 97 -t 98 -t 99 -t 101 -t 102 -t 103 --arch x64
  prebuild-windows:
    name: Prebuild Binaries for Windows
    runs-on: windows-2019
    timeout-minutes: 30
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: actions/checkout@v1
      - run: npm i
      - name: Prebuild
        run: |
          npm run apply-patches
          npm run prebuild -- --strip -r node -t 47 -t 48 -t 51 -t 57 -t 59 -t 64 -t 67 -t 72 -t 79 -t 83 -t 88 -t 93 -t 102 --arch ia32
          npm run prebuild -- --strip -r electron -t 47 -t 48 -t 49 -t 50 -t 51 -t 53 -t 54 -t 57 -t 64 -t 69 -t 70 -t 73 -t 75 -t 76 -t 80 -t 82 -t 85 -t 87 -t 89 -t 97 -t 98 -t 99 -t 101 -t 102 -t 103 --arch ia32
          npm run prebuild -- --strip -r node -t 47 -t 48 -t 51 -t 57 -t 59 -t 64 -t 67 -t 72 -t 79 -t 83 -t 88 -t 93 -t 102 --arch x64
          npm run prebuild -- --strip -r electron -t 47 -t 48 -t 49 -t 50 -t 51 -t 53 -t 54 -t 57 -t 64 -t 69 -t 70 -t 73 -t 75 -t 76 -t 80 -t 82 -t 85 -t 87 -t 89 -t 97 -t 98 -t 99 -t 101 -t 102 -t 103 --arch x64
